version: "3.5"
services:
  database:
    image: mysql:8.1
    container_name: database
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: masukdb
      MYSQL_DATABASE:  api_product
    ports:
      - "3306:3306"
    networks:
      - api_networks

networks:
  api_networks:
    driver: bridge